### ISSUE TITLE
Make the Avatar preview sticky

### ISSUE THREAD

**Issue by andersonaddo** [draftbit/avatar-generator#34]
Hi guys!
I love your product. 
Do you think you guys could make the Avatar previewer sticky? It'd make the generator a more comfortable mobile experience since users wouldn't have to scroll up all the time too see how the different choices look on their character.

**Comment by pckilgore** [comment]
Good idea!  We'd welcome a pull request implementing this, it should not be too difficult, and may actually allow us to remove some unfortunate hacks with our PNG generator requiring the avatar to be on-screen to work correctly in many browsers.
