### ISSUE TITLE
Could this be used in a custom react UI?

### ISSUE THREAD

**Issue by jay-khatri** [draftbit/avatar-generator#38]
The instructions in the README assume that I'd need to run this as a standalone application, but is there any interest in exposing this as, say, a react component? If so, I'd be happy to help out. All of the other avatar libraries aren't as polished as this one imo.

**Comment by pckilgore** [comment]
It sure could, but I would expect 1-2 small bugs along the way due to some
quirks in PNG generation that we papered over given the current deployment.

If you are interested in championing this I can advise!

I would just suggest we hash out the basic  api first, so I can get a sense
of scope before you start coding.

**Comment by jay-khatri** [comment]
Got it, makes sense! My use case is generating a deterministic avatar given an arbitrary id. Using this right now: https://avatar.windsor.io/, but the API is buggy.

I just found this: https://github.com/DiceBear/avatars/tree/v4/packages/avatars-avataaars-sprites
I'm going to give it a try, but I'll report back if I have any issues.

Appreciate the reploy

**Comment by jay-khatri** [comment]
Hey @pckilgore , I'm back! Quick question here; does this library generate a png or an svg? Or one via the other? I've been using a library for what I mentioned above, and it isn't so great, so I'm following up here.

**Comment by FlorianKoerner** [comment]
Hi @jay-khatri 

If you have questions, problems or suggestions about DiceBear Avatars, don't hesitate to contact me.

**Comment by pckilgore** [comment]
It generates a PNG.
